project 'Util.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def pods
end

target 'Util' do
    pods
end
